**DOWNLOADING THE DATASETS**
---

***Downloading NSL-KDD dataset***
---

In [1]:
# Download NSL-KDD dataset
!wget https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTrain+.txt
!wget https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTest+.txt

import pandas as pd

train = pd.read_csv("KDDTrain+.txt", header=None)
test = pd.read_csv("KDDTest+.txt", header=None)

print("Train Shape:", train.shape)
print("Test Shape:", test.shape)

train.head()

--2026-03-10 14:34:15--  https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTrain+.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19109424 (18M) [text/plain]
Saving to: ‘KDDTrain+.txt’

KDDTrain+.txt       100%[===================>]  18.22M  --.-KB/s    in 0.09s

2026-03-10 14:34:16 (214 MB/s) - ‘KDDTrain+.txt’ saved [19109424/19109424]

--2026-03-10 14:34:16--  https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTest+.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3441513 (3.3M) [text/plain]
Saving to: ‘KDDTest+.txt’

KDDTest+.txt        100%[===================>]   3.28M  --.-KB/s    in 0.04s

2026-03-10 14:34:16 (82.9 MB/s) - ‘KDDTest+.txt’ saved [3441513/3441513]

Train Shape: (125973, 43)
Test Shape: (22544, 43)

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

***Downloading UNSW-NB15 dataset***
---

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [3]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"monadarling143","key":"5a92b15ec455d6a348bd5f1eacab5ac8"}'}

In [4]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [5]:
!kaggle datasets download -d mrwellsdavid/unsw-nb15

Dataset URL: https://www.kaggle.com/datasets/mrwellsdavid/unsw-nb15
License(s): unknown
Downloading unsw-nb15.zip to /content
 56% 83.0M/149M [00:00<00:00, 870MB/s]
100% 149M/149M [00:00<00:00, 433MB/s]

In [6]:
!unzip unsw-nb15.zip

Archive:  unsw-nb15.zip
  inflating: NUSW-NB15_features.csv
  inflating: UNSW-NB15_1.csv
  inflating: UNSW-NB15_2.csv
  inflating: UNSW-NB15_3.csv
  inflating: UNSW-NB15_4.csv
  inflating: UNSW-NB15_LIST_EVENTS.csv
  inflating: UNSW_NB15_testing-set.csv
  inflating: UNSW_NB15_training-set.csv

In [7]:
!ls

kaggle.json		UNSW-NB15_1.csv		   UNSW_NB15_testing-set.csv
KDDTest+.txt		UNSW-NB15_2.csv		   UNSW_NB15_training-set.csv
KDDTrain+.txt		UNSW-NB15_3.csv		   unsw-nb15.zip
NUSW-NB15_features.csv	UNSW-NB15_4.csv
sample_data		UNSW-NB15_LIST_EVENTS.csv

In [8]:
import pandas as pd

unsw_train = pd.read_csv("UNSW_NB15_training-set.csv")
unsw_test = pd.read_csv("UNSW_NB15_testing-set.csv")

print(unsw_train.shape)
print(unsw_test.shape)

unsw_train.head()

(82332, 45)
(175341, 45)

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

***Downloading CICIDS2017 dataset***
---

In [9]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [10]:
!kaggle datasets download -d chethuhn/network-intrusion-dataset

Dataset URL: https://www.kaggle.com/datasets/chethuhn/network-intrusion-dataset
License(s): CC0-1.0
Downloading network-intrusion-dataset.zip to /content
 95% 219M/230M [00:00<00:00, 469MB/s]
100% 230M/230M [00:00<00:00, 503MB/s]

In [11]:
!unzip network-intrusion-dataset.zip

Archive:  network-intrusion-dataset.zip
  inflating: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
  inflating: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
  inflating: Friday-WorkingHours-Morning.pcap_ISCX.csv
  inflating: Monday-WorkingHours.pcap_ISCX.csv
  inflating: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
  inflating: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
  inflating: Tuesday-WorkingHours.pcap_ISCX.csv
  inflating: Wednesday-workingHours.pcap_ISCX.csv

In [12]:
import pandas as pd

df = pd.read_csv("Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")
print(df.shape)

df.head()

(225745, 79)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN